fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(
            tauri_build::AppManifest::new().commands(&[
                "scan_plugins",
                "install_plugin",
                "save_market_zip",
                "pack_plugin",
                "toggle_plugin",
                "set_plugin_sort",
                "uninstall_plugin",
                "plugin_invoke",
                "plugin_exit",
                "get_plugin_server_port",
                "get_plugin_server_url",
                "get_plugin_icon_url",
                "create_plugin_webview",
                "read_config",
                "write_config",
                "read_window_state",
                "write_window_state",
                "save_skin",
                "list_skins",
                "delete_skin",
                "save_icon",
                "get_app_icon",
                "delete_icon",
                "get_app_defaults",
                "apply_update",
                "get_update_status",
                "fetch_version_json",
            ]),
        ),
    )
    .expect("failed to build tauri application");
}
